# Generated by Django 5.2 on 2025-04-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costumer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(default=1001, max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("costumer", "bill_date")},
        ),
    ]
